Add CreateLocation to app proto
viamrobotics/api pull request #102
Opened 2022-11-08 22:12 UTC by DTCurrie

Adds the CreateLocation call to the `app.proto` to allow creation of locations via `gRPC`

2022-11-08 22:13 UTC, AdamMagaluk commented on proto/viam/app/v1/app.proto
> +  optional string org_id = 2;
Is there a reason we cannot just make this required? ListLocations has it already.

2022-11-08 22:13 UTC, AdamMagaluk commented on proto/viam/app/v1/app.proto
> +  optional string org_id = 2;
org_id -> organization_id

2022-11-08 22:14 UTC, AdamMagaluk commented on proto/viam/app/v1/app.proto
> +  string name = 1;
nit: Swap the order of name and organization.

2022-11-08 22:15 UTC, AdamMagaluk commented on proto/viam/app/v1/app.proto
> +  string id = 1;
Let's just return the Location created.

2022-11-08 22:16 UTC, AdamMagaluk requested changes
Minor changes.

2022-11-08 22:30 UTC, AdamMagaluk approved these changes

2022-11-08 22:32 UTC, DTCurrie commented
@edaniels I ran `make dist/buf` and am not seeing any changes on my machine.

2022-11-09 17:20 UTC, DTCurrie commented
> @edaniels @stevebriskin I ran `make dist/buf` and am not seeing any changes on my machine.

Just needed to run `make setup` again.

2022-11-09 17:20 UTC, merged