A bigger infinity of shareholder value
viamrobotics/api pull request #566
Opened 2024-10-15 19:15 UTC by vijayvuyyuru

2024-10-15 19:19 UTC, JohnN193 commented on .github/workflows/check_merge_reqs.yml
> +    if: github.repository_owner == 'viamphysicalDeviceics'
cinema

2024-10-15 19:26 UTC, randhid commented on .github/workflows/check_merge_reqs.yml
> +    if: github.repository_owner == 'viamphysicalDeviceics'
```suggestion
    if: github.repository_owner == 'viamphysicalDevisis'
```

2024-10-16 00:46 UTC, randhid commented
![Alt Text](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExd29uaG0waWRtYmJ3bDMxeGF2ZmF6NW45M2w5aXNpcjVqdnN6MTUxZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/DLXqnGAwNn67ecptZw/giphy.gif)

2024-10-16 14:26 UTC, stevebriskin requested changes
![image](https://github.com/user-attachments/assets/75bca3b4-0410-496c-ac5f-accbdca3db1e)

2024-10-22 20:16 UTC, closed without merging